popup form + open + close on esc & clickout
Sashikbear/playground-2 pull request #12
Opened 2022-01-21 12:20 UTC by benyossef27

hi everybody!
check out the popup i made for work
(hope i'm doning this right)
shabat shalom

2022-01-22 12:47 UTC, resdenia commented
Hey! Thank you! @benyossef27  nice job!!!
I would add probably some small comments to PR
But looks amazing!

2022-01-22 14:20 UTC, resdenia requested changes
Please see my comment. I assume it make cleaner your PR

2022-01-22 14:20 UTC, resdenia commented on work/blocks/popup/__button/popup__button.css
> +    height: 42px;
In that case you have duplicate of height and width.

2022-01-22 19:32 UTC, MariaKonstantinov approved these changes

2022-01-22 19:46 UTC, resdenia approved these changes
Nice! From my end I can approve.

2022-01-24 13:47 UTC, Sashikbear approved these changes
Awesome work, please merge

2022-01-24 13:57 UTC, Omriruvio approved these changes
Very nice, good job :)

2022-01-24 17:27 UTC, resdenia commented
@benyossef27  Hey, can you please merge your changes! Thank you for your work.

2022-01-24 17:27 UTC, merged