Populate blog from API
Sashikbear/playground-2 pull request #14
Opened 2022-01-24 15:10 UTC by Sashikbear

Hey, guys, please check my work with API and tell me if the code is optimised and readable enough. Thanks!

2022-01-24 17:18 UTC, resdenia commented
Amazing work @Sashikbear   it's advanced level but you did it very nice!!
I would leave several comments and would ask you to go over)
Thank you!

2022-01-24 17:25 UTC, resdenia requested changes
Thank you again! everything is good. Just add 2 comments to impprove our project.

2022-01-24 17:25 UTC, resdenia commented on blog/scripts/blog.js
> +            blogpostTitle.textContent = post.title;
to make it more clear you can check this article 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-01-24 17:25 UTC, resdenia commented on blog/scripts/blog.js
> +      });
If we are using then syntax it's really important to have ` .catch` for then, to handle error state.  in our case we need to console.log error.

2022-01-25 09:55 UTC, Sashikbear commented on blog/scripts/blog.js
> +      });
ok, fixing it the following syntax:
 .catch((error) => {
      console.error("Error:", error);
    });

2022-01-25 10:08 UTC, Sashikbear commented on blog/scripts/blog.js
> +            blogpostTitle.textContent = post.title;
If I understood the idea correctly, refactoring with the following syntax:
 const blog = {
          title: post.title,
          year: post.userId,
          type: post.id,
          text: post.body,
        };
        const { title, year, type, text } = blog;

2022-01-26 12:19 UTC, resdenia approved these changes
Amazing work! Can Approve

2022-01-26 12:26 UTC, merged